### ISSUE TITLE
Utilisateurs

### ISSUE THREAD

**Issue by awalex** [unexceptednavyshower/oddly-api#1]
## Model

Be careful about user's model. Django, in his own default, work with a "User" model, which is used
to handle the django-admin mecanism. It has a authentification system as well. ( you should read the doc )

But here, we're splitting everything so we don't want the extend  this User model. So dont call User model User, please, god no. It will break everything.

So a user got :
* Name
* Surname
* Mail
* Password
* Profil pic ?

Don't forget to redefine save function to hash the password.

**Comment by dackmin** [comment]
outdated
